//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namics.Foundation.Logger.Processors.DatabaseLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseLogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseLogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Namics.Foundation.Logger.Processors.DatabaseLog.DatabaseLogResources", typeof(DatabaseLogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [dbo].[DatabaseLog] ADD  CONSTRAINT [DF_DatabaseLog_Id]  DEFAULT (newid()) FOR [Id].
        /// </summary>
        internal static string AddTableContraintCommand {
            get {
                return ResourceManager.GetString("AddTableContraintCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM INFORMATION_SCHEMA.TABLES where TABLE_NAME = &apos;DatabaseLog&apos;.
        /// </summary>
        internal static string CheckTableExistsCommand {
            get {
                return ResourceManager.GetString("CheckTableExistsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [dbo].[DatabaseLog]
        ///           ([Type]
        ///           ,[Machine]
        ///           ,[IISPool]
        ///           ,[Message]
        ///           ,[ExceptionMessage]
        ///           ,[InnerExceptionMessage]
        ///           ,[LineNumber]
        ///           ,[Caller]
        ///           ,[StackTrace]
        ///           ,[RequestUrl]
        ///           ,[CreateDate])
        ///     VALUES
        ///           (&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;,&apos;{3}&apos;,&apos;{4}&apos;,&apos;{5}&apos;,&apos;{6}&apos;,&apos;{7}&apos;,&apos;{8}&apos;,&apos;{9}&apos;,@date).
        /// </summary>
        internal static string CreateLogEntryCommand {
            get {
                return ResourceManager.GetString("CreateLogEntryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DatabaseLog](
        ///	[Id] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
        ///	[Type] [nvarchar](10) NOT NULL,
        ///	[Machine] [nvarchar](50) NOT NULL,
        ///                   [IISPool] [nvarchar](50) NULL,
        ///	[Message] [nvarchar](max) NULL,
        ///	[ExceptionMessage] [nvarchar](max) NULL,
        ///	[InnerExceptionMessage] [nvarchar](max) NULL,
        ///	[LineNumber] [int] NULL,
        ///	[Caller] [nvarchar](250) NULL,
        ///	[StackTrace] [nvarchar](max) NULL,
        ///                   [RequestUrl] [nvarchar](max) NULL,
        ///	[CreateDate] [datetime] NOT N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTableCommand {
            get {
                return ResourceManager.GetString("CreateTableCommand", resourceCulture);
            }
        }
    }
}
